rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - checkstyle
      - units (8)
      - units (11)
      - dependencies (8)
      - dependencies (11)
      - linkage-monitor
      - clirr
      - cla/google
  - pattern: 1.31.4-sp
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - checkstyle
      - units (8)
      - units (11)
      - dependencies (8)
      - dependencies (11)
      - linkage-monitor
      - clirr
      - cla/google
  - pattern: 1.32.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - checkstyle
      - units (8)
      - units (11)
      - dependencies (8)
      - dependencies (11)
      - linkage-monitor
      - clirr
      - cla/google
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
